# <center>Laboratorium 1<br>Metody Numeryczne</center>

Biblioteki niezbędne do wykonania zadania:

(wykonanie tego bloku zapewnia do nich dostęp w kolejnych blokach)

In [4]:
import numpy as np
import math
import scipy

Przydatne w trakcie zajęć mogą okazać się metody macierzy z pakietu Numpy, takie jak na przykład długość wektora - *[len]()* czy rozmiar macierzy -
*[shape](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.shape.html#numpy.ndarray.shape)*. Poniższy kod ilustruje ich podstawowe działanie. Dodatkowe metody obiektu $ndarray$ można znaleźć w oficjalnej *[dokumentacji](https://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)*.

In [12]:
vector = np.array([1, 2, 3])
print('Wektor:')
print(vector)
print('Długość:', len(vector))
print('Rozmiar:', vector.shape, '\n')

matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print('Macierz:')
print(matrix)
print('Rozmiar:', matrix.shape)

Wektor:
[1 2 3]
Długość: 3
Rozmiar: (3,) 

Macierz:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rozmiar: (3, 3)


***Zadanie 1.***  
Zaimplementuj funkcję $cylinder\_area$ tak by zwracała pole powierzchni walca o promieniu podstawy $r$ i wysokości $h$. Stała $\pi$ jest zdefiniowana np. w bibliotece *[math](https://docs.python.org/3/library/math.html#constants)*. Jeżeli nie da się policzyć pola funkcja powinna zwracać wartość *NaN*. Sprawdź działanie zaimplementowanej funkcji dla dowolnych wartości w tym notatniku.



In [2]:
#Użyłem "nan" z modułu NumPy, dlatego też wyświetlana wartość to "nan" a nie "NaN".


def cylinder_area(r:float,h:float):
    if r>=0.0 and h>= 0.0:
        return 2*math.pi*r**2+2*math.pi*r*h
    else:
        return np.nan


print(cylinder_area(1,2))
print (cylinder_area(-1,0))
print (cylinder_area(1,-2))
print (cylinder_area(-1,-1))
print (cylinder_area(0,2))

18.84955592153876
nan
nan
nan
0.0


***Zadanie 2.***  
Wygeneruj dowolne ciągi arytmetyczny o kroku różnym od jeden i niebędącym liczbą całkowitą, używając w tym celu funkcji *[arange](https://docs.scipy.org/doc/numpy/reference/generated/numpy.arange.html)* oraz *[linspace](https://docs.scipy.org/doc/numpy-1.10.0/reference/generated/numpy.linspace.html)*. Wypisz go i przeanalizuj otrzymane rezultaty.

In [7]:
#analiza otrzymanych rezultatów jako tekst pod kodem

series1 = np.arange(3,20,2)   
series2= np.linspace(2,20,num=10)    

print("Series 1: ",series1)
print("Series 2: ",series2)

Series 1:  [ 3  5  7  9 11 13 15 17 19]
Series 2:  [ 2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


Analiza otrzymanych rezultatów:

Główną różnicą, jest to, że gdy używamy linspace, możemy podać wartość początkową, końcową oraz liczbę elementów i tworzony jest ciąg, którego krok jest obliczany automatycznie poprzez równomierne rozmieszeczenie liczb pomiędzy wartością początkową oraz końcową (odległości pomiędzy następnymi liczbami są równe), a w przypadku użyciu arange sami podajemy krok, wartość początkową oraz końcową a automatycznie dobierana jest ilość wygenerowanych liczb.

Oprócz tego, różnicą którą można od razu zauważyć jest to, że w przypadku użycia linspace zamiast arange liczby generowane są z kropką.

W dokumentacji udało mi się wyczytać, że gdy używamy kroku, który nie jest liczbą całkowitą, powinniśmy używać funkcji linspace zamiast arange.

***Zadanie 3.***  
Zaimplementuj funkcję $fib$ zwracającą wektor pierszych n elementów *[ciągu Fibonnaciego](https://pl.wikipedia.org/wiki/Ci%C4%85g_Fibonacciego)*, jeżeli nie jest to możliwe funkcja powinna zwrócić wartość *None*.

In [19]:
def fib(n:int):  
    if type(n)!=int:
        return None
    if n==0:
        return None
    if n==1:
        return [1]
    if n>=1:
        vect=np.ones((n,1))
        a,b = (1,1)
        for i in range (n):
            vect[i]=a
            a,b = b, a+b
        return np.transpose(vect)
    if n<0:
        return None


print ("Ciąg nie jest generowany gdy liczba elementów wynosi 0: ",fib(0))
print ("Ciąg fibonacciego dla 1 elemtnu: ",fib(1))
print ("Ciąg nie jest generowany gdy podamy ujemną liczbę elemetów: ",fib(-2))
print ("Ciąg fibonacciego dla 8 elemtnów: ",fib(8))
print ("Ciąg nie jest generowany gdy podamy liczbę typu float zamiast int: ",fib(8.0))
print ("Ciąg fibonacciego dla 0 elemtnów: ",fib(15))


Ciąg nie jest generowany gdy liczba elementów wynosi 0:  None
Ciąg fibonacciego dla 1 elemtnu:  [1]
Ciąg nie jest generowany gdy podamy ujemną liczbę elemetów:  None
Ciąg fibonacciego dla 8 elemtnów:  [[ 1.  1.  2.  3.  5.  8. 13. 21.]]
Ciąg nie jest generowany gdy podamy liczbę typu float zamiast int:  None
Ciąg fibonacciego dla 0 elemtnów:  [[  1.   1.   2.   3.   5.   8.  13.  21.  34.  55.  89. 144. 233. 377.
  610.]]


***Zadanie 4.***  
Napisz funkję $matrix\_calculations$ która jako argument przyjmuje dowolną wartość liczbową *a* i tworzy macierz:  
  
$\mathbf{M} =\left[ \begin{matrix}
a & 1 & -a\\
0 & 1 & 1\\
-a & a & 1
\end{matrix}\right]
$    
   
Dla zadeklarowanej macierzy wyznacz numerycznie macierz odwrotną $\mathbf{Minv}$ (jeżeli nie istnieje taka macierz wartość wynosi NaN), macierz transponowaną $\mathbf{Mt}$ i wyznacznik macierzy $\mathbf{Mdet}$. Zwróć otrzymane wartości w postaci krotki postaci $(\mathbf{Minv}, \mathbf{Mt}, \mathbf{Mdet})$.  Wypisz otrzymane wyniki. 
  
***Wskazówki:*** Do tworzenia obiektów mających własności macierzy w języku Python używa się klasy *[array](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.array.html)* z pakietu *[numpy](http://www.numpy.org/)*, przykładowe użycie:

In [2]:
import numpy as np # słowo kluczowe "as" oznacza przesłania nazwę numpy i pozwala  
a = np.array([1, 2, 3])
b = np.array([[1], [2], [3]])
A = np.array([[1,2],[3,4]])
print("Wektor poziomy:\n {0}".format(a))
print("Wektor pionowy:\n {0}".format(b))
print("Macierz:\n {0}".format(A))

Wektor poziomy:
 [1 2 3]
Wektor pionowy:
 [[1]
 [2]
 [3]]
Macierz:
 [[1 2]
 [3 4]]


Do wykonania operacji odwracania macierzy należy użyć funkcji *[inv](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linalg.inv.html)*, do obliczenia wyznacznika macierzy stosuje się funkcję *[det](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.linalg.det.html)*  z bliblioteki *[linalg](https://docs.scipy.org/doc/numpy/reference/routines.linalg.html)*. Natomiast transpozycję macierzy wykonujemy przez funkcję *[transpose](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.transpose.html)* której skrucona wersja to $M.T$ z pakietu *numpy*.  
    
*Ciekawostka:* Python natywnie nie zawiera struktury danych typu tablica, na poziomie języka jest to rozwiązane poprzez strukturę listy list do której elementów odwołuje się poprzez indeksy jak w C/C++.

In [9]:
def matrix_calculations(a:float):
    M=np.array([[a, 1, -a],
                [0, 1, 1],
                [-a, a, 1]]) 
    
    Mt= np.transpose(M) # Mt= M.T
    Mdet = np.linalg.det(M)
    
    if Mdet==0:
        Minv=np.nan
    else:
        Minv = np.linalg.inv(M)

    return (Minv, Mt, Mdet)

print("Wynik dla a=0: ",matrix_calculations(0),"\n\n") #gdy wyznacznik wynosi 0 nie można wykonać operacji odwracania macierzy, więc wyświetlana jest wartość nan


print("Wynik dla a=2: ",matrix_calculations(2.0),"\n\n")

Wynik dla a=0:  (nan, array([[0, 0, 0],
       [1, 1, 0],
       [0, 1, 1]]), 0.0) 


Wynik dla a=2:  (array([[ 0.125,  0.625, -0.375],
       [ 0.25 ,  0.25 ,  0.25 ],
       [-0.25 ,  0.75 , -0.25 ]]), array([[ 2.,  0., -2.],
       [ 1.,  1.,  2.],
       [-2.,  1.,  1.]]), -7.999999999999998) 




***Zadanie 5.***  
Stwórz w noataniku macierz:  
$\mathbf{M} =\left[ \begin{matrix}
3 & 1 & -2 & 4\\
0 & 1 & 1 & 5\\
-2 & 1 & 1 & 6\\
4 & 3 & 0 & 1\\
\end{matrix}\right]
$   
Wypisz przy pomocy funkcji *print* następujące elementy macierzy $\mathbf{M}$: $\mathbf{M}_{1,1},\mathbf{M}_{3,3},\mathbf{M}_{3,2}$. Zdefiniuj wektor $\mathbf{w1}$ którego elementy to trzecia kolumna macierzy $\mathbf{M}$ oraz wektor $\mathbf{w2}$ który składa się z drugiego wiersza tej macierzy.  
  
***Wskazówki:***
Tablice z pakietu *numpy* są indeksowane od zera a do każdego elementu można odwołać się poprzez jego indeks. Przykład użycie


In [10]:
# Inicjalizacja macierzy do przykładu
P = np.array([[1,3,2],[3,4, 6],[7,8,9]])
print("Macierz P=\n{0}".format(P))
# wyciągnięcie trzeciej kolumny 
wektor1 = P[:,2]
# wyciągnięcie trzeciego wiersza 
wektor2 = P[2,:]
print("Elementy trzeciej kolumny:\n {0}".format(wektor1))
print("Elementy trzeciego wiersza:\n {0}".format(wektor2))

Macierz P=
[[1 3 2]
 [3 4 6]
 [7 8 9]]
Elementy trzeciej kolumny:
 [2 6 9]
Elementy trzeciego wiersza:
 [7 8 9]


Dodatkowo twórcy biblioteki umożliwiają użytkownikowi na manipulację elementami tablicy poprzez operator ':', więcej szczegółów na temat jego użycia w artykule [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users).

In [12]:
M=np.array([[3, 1, -2, 4],
   [0, 1, 1, 5],
   [-2, 1, 1, 6],
   [4, 3, 0, 1]])

print("Macierz M=\n{0}".format(M))

print("M(1,1) = ",M[0,0]) #wypisanie elementu M(1,1)
print("M(3,3) = ",M[2,2]) #wypisanie elementu M(3,3)
print("M(3,2) = ",M[2,1]) #wypisanie elementu M(3,2)

w1=M[:,2] # utworzenie wektora będącego 3 kolumną macierzy M
w2=M[1,:] # utworzenie wektora będącego 2 wierszem macierzy M

Macierz M=
[[ 3  1 -2  4]
 [ 0  1  1  5]
 [-2  1  1  6]
 [ 4  3  0  1]]
M(1,1) =  3
M(3,3) =  1
M(3,2) =  1


***Zadanie 6.***   
Uzupełnij funkcję $custom\_matrix$, tak by parametry m, n określały wymiary macierzy wynikowej, która
będzie wypełniona w/g algorytmu: jeśli indeks wiersza jest większy od indeksu kolumny
wartością komórki jest indeks wiersza, w przeciwnym wypadku wartością komórki jest indeks
kolumny. Funkcja jako wynik powinna zwracać uzupełnioną macierz, jeżeli nie jest to możliwe to powinna zwrócić *None*. Na koniec wyświetlić wynikową macierz dla dowolnych argumentów $m$, $n$ z przedziału $\langle3,7\rangle$.
  
***Wskazówka:*** Inicjalizacja pustej macierz wykonywana jest w pakiecie Numpy przy pomocy funkcji  *[zeros](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.zeros.html)*, zaś macierzy składającej się z jedynek *[ones](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ones.html)*.

In [18]:
zero_matrix = np.zeros((2, 2))
ones_matrix = np.ones((3,1))

print('zero_matrix: \n{}'.format(zero_matrix))
print('ones_matrix: \n{}'.format(ones_matrix))

zero_matrix: 
[[0. 0.]
 [0. 0.]]
ones_matrix: 
[[1.]
 [1.]
 [1.]]


In [13]:
def custom_matrix(m:int, n:int):
    if type(m)!=int or type(n)!=int:
        return None
    
    if m>0 and n>0:
        M=np.ones((m,n))
        for i in range (m):
            for j in range (n):
                if i>j:
                    M[i,j]=i
                else:
                    M[i,j]=j
        return M
    else:
        return None

print("Macierz 5x4: ",custom_matrix(5,4))
print("Macierz 0x4: ",custom_matrix(0,4))

Macierz 5x4:  [[0. 1. 2. 3.]
 [1. 1. 2. 3.]
 [2. 2. 2. 3.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]]
Macierz 0x4:  None


***Zadanie 7.***

Biblioteka Numpy posiada własne metody, pozwalające na szybsze i wygotniejsze wykonywanie operacji na wektorach i macierzach. Kolejne zadania mają na celu przećwiczenie tych metod. Zamiast samemu implementować mnożenie macierzy, należy skorzystać właśnie z wbudowanych funkcji Numpy. Najbardzie podstawowe z nich to *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*, *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* oraz *[np.matmul](https://docs.scipy.org/doc/numpy-1.15.1/reference/generated/numpy.matmul.html)*. Przed wykonaniem zadania należy zapoznać się z ich dokumentacją, aby stosować poprawną funkcję do danego typu mnożenia. Dodatkowo ciekawą i użyteczną funkcjonalnością Numpy, wykorzystywaną niekiedy przy dodawaniu macierzy jest *broadcasting*, proszę o zapoznaie się z opisem:  *[[1]](https://docs.scipy.org/doc/numpy-1.15.0/user/basics.broadcasting.html)* *[[2]](https://www.tutorialspoint.com/numpy/numpy_broadcasting.htm)*.

Zainicjalizować dwa wektory $v_1$ i $v_2$:

$v_1 = \begin{bmatrix}1\\3\\13\end{bmatrix} \quad v_2 = \begin{bmatrix}8\\5\\-2\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $4*v_1$
- $-v_2 + \begin{bmatrix}2\\2\\2\end{bmatrix}$
- $v_1 \circ v_2$ (w sensie mnożenia macierzy, tzw. mnożenie macierzy w sensie Cauchy’ego)
- $v_1 * v_2$ (w sensie mnożenia Hadamarda (element-wise))

***Wskazówki:*** Warto wiedzieć o *[np.dot](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.dot.html)* i *[np.multiply](https://docs.scipy.org/doc/numpy-1.15.0/reference/generated/numpy.multiply.html)*. Zbadać jak zachowuje się przeciążony operator mnożenia $*$ oraz $@$ dla macierzy $ndarray$.

In [14]:
v1 = np.array([[1,3,13]]).T
v2 = np.array([[8,5,-2]]).T
print ("4*v1= \n =",4*v1,"\n")
print ("-v2+[[2],[2],[2]]= \n =",-v2+[[2],[2],[2]],"\n")
print ("v1 * v2= \n =", v1*v2,"\n")
print ("Inny sposób: v1 * v2= \n =", np.multiply(v1,v2),"\n")
# print("v1 o v2= \n =",v1@v2,"\n")  - nie można wykonać (brak zgodności wymiarów)
#multiply działa w ten sposób, że wykonuje mnożenie element-wise, matmul jest najlepszy do działań na macierzach 2-D


4*v1= 
 = [[ 4]
 [12]
 [52]] 

-v2+[[2],[2],[2]]= 
 = [[-6]
 [-3]
 [ 4]] 

v1 * v2= 
 = [[  8]
 [ 15]
 [-26]] 

Inny sposób: v1 * v2= 
 = [[  8]
 [ 15]
 [-26]] 



Wykonanie operacji mnożenia macierzowego na powyższych wektorach jest niemożliwe, ponieważ nie mamy zgodności odpowiednich wymiarów.

Operator @ dokonuje mnożenia macierzowego (w sensie Cauchy'ego), operator * dokonuje mnożenia element-wise, czyli działa tak samo jak numpy.multiply()

***Zadanie 8.***
Zainicjalizować macierz $M_1$:

$M_1 = \begin{bmatrix}1&-7&3\\-12&3&4\\5&13&-3\end{bmatrix}$

Następnie wykonać operacje i wypisać ich wynik:
- $3M_1$
- $3M_1 + \begin{bmatrix}1&1&1\\1&1&1\\1&1&1\end{bmatrix}$
- $M_1^T$
- $M_1 \circ v_1$ 
- $v_2^T \circ M_1$

In [15]:
M1=np.array([[1, -7, 3],[-12, 3, 4],[5, 13, -3]])
print ("3*M1 = \n =",3*M1,"\n")
print ("3*M1 + J = \n =",3*M1+np.ones((3,3)),"\n")
print ("M1' = \n =",np.transpose(M1),"\n")
print ("M1 o v1 = \n",M1@v1,"\n")
print ("v2' o M1 = \n", np.transpose(v2)@M1, "\n")

3*M1 = 
 = [[  3 -21   9]
 [-36   9  12]
 [ 15  39  -9]] 

3*M1 + J = 
 = [[  4. -20.  10.]
 [-35.  10.  13.]
 [ 16.  40.  -8.]] 

M1' = 
 = [[  1 -12   5]
 [ -7   3  13]
 [  3   4  -3]] 

M1 o v1 = 
 [[19]
 [49]
 [ 5]] 

v2' o M1 = 
 [[-62 -67  50]] 



Materiały uzupełniające:
- [Scipy Lecture Notes](http://www.scipy-lectures.org/index.html)
- [NumPy for Matlab users](https://docs.scipy.org/doc/numpy/user/numpy-for-matlab-users.html#numpy-for-matlab-users)
- [Python Tutorial - W3Schools](https://www.w3schools.com/python/default.asp)
- [NumPy](https://www.numpy.org)
- [Matplotlib](https://matplotlib.org/)
- [Anaconda](https://www.anaconda.com/)
- [Learn Python for Data Science](https://www.datacamp.com/learn-python-with-anaconda?utm_source=Anaconda_download&utm_campaign=datacamp_training&utm_medium=banner)
- [Learn Python](https://www.learnpython.org/)
- [Wujek Google](https://google.pl) i [Ciocia Wikipedia](https://pl.wikipedia.org/wiki/Wikipedia:Strona_g%C5%82%C3%B3wna)